env:
  symbol: BTCUSDT
  exec_tf: 5m
  window_size: 64
  fee_rate: 0.0004
  slippage_bp: 1.0
  reward_dd_penalty: 0.0
  normalize_obs: true

agent:
  lr: 0.0003
  gamma: 0.99
  gae_lambda: 0.95
  clip_ratio: 0.2
  entropy_coef: 0.0
  value_coef: 0.5
  hidden: 256
  device: cpu

trainer:
  total_steps: 10000000
  rollout_length: 2048
  minibatch_size: 8192
  epochs_per_update: 4
  checkpoint_interval: 200000
  log_interval: 10000
  seed: 1337
  output_dir: reports/train

cv:
  mode: walk_forward
  folds: 5
  purge_pct: 0.05
  embargo_pct: 0.05
  select_metric: sharpe
