exchange: "bitget"
symbols: ["BTC/USDT","ETH/USDT"]
timeframes: ["1m","5m","15m","1h","4h","1d"]
years_back: 5
store:
  parquet_root: "data/warehouse"
  compression: "zstd"
rt:
  influx:
    url: "http://localhost:8086"
    org: "bot_trading"
    bucket: "market_rt"
    token_env: "INFLUX_TOKEN"
postgres:
  dsn_env: "PG_DSN"
redis:
  url_env: "REDIS_URL"
