features:
  ema: [20, 50, 200]
  sma: [20, 50, 200]
  rsi: { period: 14 }
  macd: { fast: 12, slow: 26, signal: 9 }
  atr: { period: 14 }
  bbands: { period: 20, dev: 2.0 }
  supertrend: { period: 10, multiplier: 3.0 }
  obv: true
  vwap: true
naming:
  prefix: "ta"
  sep: "_"
nan_policy:
  fill_method: "ffill"
  drop_initial: true
timeframes:
  direction: ["1d", "4h"]
  confirmation: ["1h", "15m"]
  execution: ["5m", "1m"]
