# risk.yaml
# Descripción: Parámetros de gestión de riesgo autónoma (comunes, spot y futuros).
# Ubicación: config/risk.yaml
# La consume base_env/risk para sizing, exposición, apalancamiento y circuit breakers.
common:
  daily_max_drawdown_pct: 5.0
  exposure_max_abs: 1.0           # 1.0 = 100% del equity (spot). En futuros se interpreta con margen.
  circuit_breakers:
    data_quality_pause: true
    inconsistent_signals_pause: true

spot:
  risk_pct_per_trade: 0.5         # % del equity_quote en riesgo por operación
  trailing:
    enabled: true
    atr_multiple: 1.0

futures:
  max_initial_leverage: 3
  risk_pct_per_trade: 0.5
  margin_buffer_pct: 10.0
  trailing:
    enabled: true
    atr_multiple: 1.0
