# =========================
# config/risk.yaml (v9.1.8)
# Perfiles de riesgo listos para entrenar y "desatascar" aperturas
# =========================

# Selecciona el perfil activo:
active_profile: starter_safe   # opciones: starter_safe | train_loose

# -------------------------
# Perfil CONSERVADOR (recomendado para empezar a tradear y validar flujo)
# -------------------------
starter_safe:
  common:
    # --- Niveles mínimos de estructura del trade ---
    default_levels:
      min_sl_pct: 0.35          # SL mínimo 0.35% (más bajo = más fácil que el sizing no caiga a 0)
      tp_r_multiple: 1.3        # TP >= 1.3x SL (menos exigente para que pase gating)
      hard_min_sl_pct: 0.25     # no permitir SL por debajo de 0.25% aunque la acción lo pida
      hard_max_sl_pct: 3.0      # limitar SL máximo (evitar operaciones absurdas)
      ttl_bars_max: 400         # caducidad máxima del trade (cierre forzado si no ha salido)

    # --- Sizing por volatilidad (ATR) ---
    sizing:
      method: atr_volatility     # atr_volatility | fixed_fraction
      risk_per_trade_pct: 0.35   # riesgo por trade (del equity) → conservador pero no ridículo
      atr_period: 14
      atr_mult_sl: 1.0           # SL ≈ 1.0 * ATR (luego respeta min_sl_pct si es mayor)
      atr_price_basis: "close"   # close | hl2 | ohlc4
      clamp_qty_to_notional: true # asegura alcanzar minNotional si train_force_min_notional=false
      max_concurrent_positions: 1 # en TRAIN para desatascar, 1 es buen comienzo

    # --- Reglas de apertura auxiliares ---
    open_rules:
      require_sl: true
      require_tp: true
      train_force_min_notional: false   # al principio, NO fuerces minNotional (evita bloqueos)
      allow_partial_fills: true
      allow_confidence_fallback_open: true # permite abrir si la confianza no llega al umbral

    # --- Cooldown y deduplicación ---
    execution_controls:
      cooldown_bars: 3            # tras cerrar/abrir, espera 3 barras de la TF de ejecución
      dedup_same_bar: true        # evita dos aperturas mismo bar_time+side
      reset_dedup_on_new_bar: true

    # --- Exposición y límites globales ---
    exposure:
      max_notional_pct: 100.0     # en TRAIN, sin límite duro sobre equity
      max_leverage_effective: 5.0 # "techo" lógico de apalancamiento efectivo en sizing

    # --- Breakers (suaves al principio) ---
    circuit_breakers:
      daily_dd_pct: 15.0          # pausa si DD diario supera 15%
      latency_ms: null            # no aplica en backtest sim
      inconsistent_signals: false

    # --- Bancarrota / Equity guard ---
    bankruptcy:
      enabled: false              # desactivado en TRAIN para no matar runs prematuramente
      threshold_pct: 5.0
      mode: "soft_reset"          # si lo activas en el futuro

    # --- Costes y fricción ---
    market_friction:
      taker_fee_bps: 10           # 0.10%
      maker_fee_bps: 2            # 0.02%
      slippage_bps: 5             # 0.05% simulado
      funding_bps_daily: 0        # ignora funding en TRAIN (o fija un valor si quieres)

    # --- Gestión dinámica de riesgo (ramp-up) ---
    ramp_up:
      enabled: true
      warmup_runs: 20             # durante los primeros N runs, baja el riesgo por trade
      warmup_risk_pct: 0.20       # % riesgo por trade durante warmup
      restore_after_runs: true

    # --- Trailing y salidas ---
    trailing:
      enabled: true
      trigger_r_multiple: 0.8     # activa trailing cuando el trade va +0.8R
      trail_step_pct: 0.15        # mueve SL un 0.15% del precio a favor
      break_even_at_r: 1.0        # mueve SL a BE al alcanzar 1R

    # --- Validaciones mínimas para evitar bloqueos tontos ---
    validations:
      min_notional_check: "warn"  # warn | block (en starter: solo avisa)
      sl_distance_check: "block"  # no permitir SL por debajo del mínimo duro
      tp_distance_check: "warn"   # TP insuficiente avisa (no bloquea) para no matar aperturas

# -------------------------
# Perfil PARA ENTRENAR (más laxo, abrirá más trades y explora)
# -------------------------
train_loose:
  common:
    default_levels:
      min_sl_pct: 0.25
      tp_r_multiple: 1.2
      hard_min_sl_pct: 0.20
      hard_max_sl_pct: 4.0
      ttl_bars_max: 600

    sizing:
      method: atr_volatility
      risk_per_trade_pct: 0.50     # explora más
      atr_period: 14
      atr_mult_sl: 0.9
      atr_price_basis: "hl2"
      clamp_qty_to_notional: true
      max_concurrent_positions: 2

    open_rules:
      require_sl: true
      require_tp: true
      train_force_min_notional: true  # en train: fuerza llegar al mínimo notional
      allow_partial_fills: true
      allow_confidence_fallback_open: true

    execution_controls:
      cooldown_bars: 2
      dedup_same_bar: true
      reset_dedup_on_new_bar: true

    exposure:
      max_notional_pct: 120.0
      max_leverage_effective: 8.0

    circuit_breakers:
      daily_dd_pct: 20.0
      latency_ms: null
      inconsistent_signals: false

    bankruptcy:
      enabled: false
      threshold_pct: 5.0
      mode: "soft_reset"

    market_friction:
      taker_fee_bps: 10
      maker_fee_bps: 2
      slippage_bps: 7
      funding_bps_daily: 0

    ramp_up:
      enabled: true
      warmup_runs: 10
      warmup_risk_pct: 0.30
      restore_after_runs: true

    trailing:
      enabled: true
      trigger_r_multiple: 0.6
      trail_step_pct: 0.20
      break_even_at_r: 0.8

    validations:
      min_notional_check: "block"
      sl_distance_check: "block"
      tp_distance_check: "warn"