swings:
  lookback_left: 5
  min_atr_k: 0.5
bos:
  buffer_atr_k: 0.1
  require_close: true
fvg:
  min_gap_atr_k: 0.1
  mode: "classic"
order_blocks:
  extend_until_mitigated: true
  max_age_bars: 1500
runtime:
  mode: "causal"   # sin lookahead
