symbols:
  - pair: "BTC/USDT"
    symbol_id: "BTCUSDT"
    min_qty: 0.0001
    tick_size: 0.1
    lot_step: 0.0001
    timeframes: ["1m","5m","15m","1h","4h","1d"]
  - pair: "ETH/USDT"
    symbol_id: "ETHUSDT"
    min_qty: 0.001
    tick_size: 0.01
    lot_step: 0.0001
    timeframes: ["1m","5m","15m","1h","4h","1d"]
