# symbols.yaml
# Descripción: Lista de símbolos que trabajará el bot (spot y/o futuros) y sus filtros del exchange.
# Ubicación: config/symbols.yaml
# La consume base_env (filtros, tf habilitados) y los data loaders (descarga/validación de histórico).
symbols:
  - symbol: BTCUSDT
    mode: train_spot
    enabled_tfs: ["1m","5m"]
    leverage:
      min: 2.0
      max: 25.0
      step: 1.0
      default: 5.0
    filters:
      tickSize: 0.1
      lotStep: 0.0001
      minNotional: 5.0

# - name: ETHUSDT
#    mode: train_futures
#    enabled: true
#    enabled_tfs: ["1m","5m","15m","1h","4h","1d"]
#    leverage:
#      min: 2.0       # mínimo permitido por YAML
#      max: 25.0      # máximo permitido por YAML
#      step: 1.0      # granularidad (1x -> niveles enteros). Cambia aquí sin tocar .py
#      default: 5.0   # valor de arranque (sólo inicial; luego el agente decide)
#    filters:
#      tickSize: 0.01
#      lotStep: 0.001
#      minNotional: 5.0
