# symbols.yaml
# Descripción: Lista de símbolos que trabajará el bot (spot y/o futuros) y sus filtros del exchange.
# Ubicación: config/symbols.yaml
# La consume base_env (filtros, tf habilitados) y los data loaders (descarga/validación de histórico).
symbols:
  # ← DESACTIVADO: Solo entrenar futuros por ahora
  # - symbol: BTCUSDT
  #   mode: train_spot
  #   history_years: 5   # ← NUEVO: Años de histórico requeridos
  #   enabled_tfs: ["1m","5m","15m","1h"]
  #   allow_shorts: true  # ← NUEVO: Habilitar shorts en spot (margen)
  #   filters:
  #     tickSize: 0.1
  #     lotStep: 0.0001
  #     minNotional: 1.0  # ← REDUCIDO: De 5.0 a 1.0 para permitir órdenes más pequeñas
  
  # ← ACTIVO: Configuración para FUTUROS con leverage dinámico
  - symbol: BTCUSDT
    mode: train_futures
    history_years: 5
    enabled_tfs: ["1m","5m","15m","1h","4h"]
    allow_shorts: true
    filters:
      tickSize: 0.1
      lotStep: 0.0001
      minNotional: 5.0  # ← CORREGIDO: minNotional real de Bitget para BTCUSDT futures
    leverage:
      min: 2.0
      max: 25.0
      step: 1.0
      default: 3.0                   # ← AUMENTADO: De 2.0 a 3.0 para más flexibilidad
      dynamic: true                  # ← NUEVO: Permitir que el bot elija leverage dinámicamente